services:
  - type: web
    name: telegram-kring-test1-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        value: 7953006027:AAHjV_dN5J9_a77bLbIdk-HTfQYrcrFDN4k
